#!/usr/bin/bash
# vim: filetype=sh

if [ "$EUID" -ne 0 ];then
	printf "Please run as root\n"
	exit 1
fi

if ! [ -f "wpe.py" ]; then
	printf "Script not found\n"
	exit 1
fi

# provide --gif if you want gif support
if [ "$1" == "--gif" ]; then
    if [ -f "include/foo-Wallpaper-Feh-Gif/back4.sh" ]; then
        printf "Installing back4 ... "
        chmod +x include/foo-Wallpaper-Feh-Gif/back4.sh 
        cp include/foo-Wallpaper-Feh-Gif/back4.sh /usr/bin/back4
        if [ "$?" -eq 0 ]; then
            printf "done\n"
        else
            printf "error\n"
            exit 1
        fi
    fi
fi


printf "Installing wpe ... "
chmod +x wpe.py
cp wpe.py /usr/bin/wpe

if [ "$?" -eq 0 ]; then
    printf "done\n"
    printf "Copying config ... "
    cp wpe.json $HOME/.config/wpe.json
    if [ "$?" -eq 0 ]; then
        printf "done\n\n"
    else
        printf "error\n\n"
    fi
	printf "wpe.py is now available as wpe\n"
	exit 0
else
	printf "error\n\n"
	printf "Something went wrong\n"
	exit 1
fi
